export const NUANCE_COLORS: Record<string, string> = {
  LRN: "#003189",
  LFI: "#cc2443",
  LSOC: "#e75480",
  LLR: "#0066cc",
  LREN: "#ffbe00",
  LECO: "#22c55e",
  LCOM: "#8b0000",
  LEXG: "#dc2626",
  LEXD: "#172554",
  LDVG: "#f472b6",
  LDVD: "#60a5fa",
  LDIV: "#6b7280",
  LHOR: "#0d9488",
  LMDM: "#d97706",
  LREC: "#65a30d",
  LREG: "#4ade80",
  LUC: "#06b6d4",
  LUD: "#38bdf8",
  LUDI: "#64748b",
  LUDR: "#4338ca",
  LUG: "#f87171",
  LUXD: "#172554",
  LVEC: "#10b981",
  LDSV: "#f97316",
  LDVC: "#eab308",
  "": "#9ca3af",
};

export const NUANCE_LABELS: Record<string, string> = {
  LRN: "Rassemblement National",
  LFI: "La France Insoumise",
  LSOC: "Parti Socialiste",
  LLR: "Les Républicains",
  LREN: "Renaissance",
  LECO: "Europe Écologie",
  LCOM: "Parti Communiste",
  LEXG: "Extrême Gauche",
  LEXD: "Extrême Droite",
  LDVG: "Divers Gauche",
  LDVD: "Divers Droite",
  LDIV: "Divers",
  LHOR: "Horizons",
  LMDM: "MoDem",
  LREC: "Régionaliste",
  LREG: "Régionaliste",
  LUC: "Union du Centre",
  LUD: "Union de la Droite",
  LUDI: "Union Divers",
  LUDR: "Union Droite Républicaine",
  LUG: "Union de la Gauche",
  LUXD: "Extrême Droite",
  LVEC: "Les Verts / Écologistes",
  LDSV: "Divers",
  LDVC: "Divers Centre",
  "": "Autre",
};

export const NO_WINNER_COLOR = "#e5e7eb";
